#!/bin/sh -f
# Enter up to 10 extra ports here. Refer to the documentation for MOREPORTS
# in the restart script, or just use that instead.
PORTS="";

# Start/stop the netmuck server.

GAMEDIR=$HOME

case "$1" in
start)	$GAMEDIR/proto/game/restart $PORTS ;;
on)	$GAMEDIR/proto/game/restart $PORTS ;;
stop)	kill `cat $GAMEDIR/proto/game/protomuck.pid` ;;
off)	kill `cat $GAMEDIR/proto/game/protomuck.pid` ;;
*)	echo "Usage: $0 start|stop"; exit 1 ;;
esac
exit 0

